---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - network.apollo.network
  resources:
  - apollonetworkpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.apollo.network
  resources:
  - apollonetworkpools/finalizers
  verbs:
  - update
- apiGroups:
  - network.apollo.network
  resources:
  - apollonetworkpools/status
  verbs:
  - get
  - patch
  - update
